import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Icon Embeded Controls",
  description: "Generated by Icon Embeded Controls",
};

import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/contexts/ThemeContext";

import DisableRightClick from "@/components/DisableRightClick";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
        <DisableRightClick />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
